language: node_js
node_js:
  - '10'

services:
  - docker

before_script:
  - make rootfs-pull

script:
  - npm run lint
  - npm run build
  - npm run test:cover -- --forceExit

after_success:
  # Upload test coverage to codecov.io
  - bash <(curl -s https://codecov.io/bash)

deploy:
  # Do a semantic release
  - provider: script
    skip_cleanup: true
    script: npx semantic-release
    on:
      branch: master
